# Generated by Django 4.1.5 on 2023-01-14 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negative_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('neutral_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('positive_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.client')),
                ('review', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.review')),
            ],
        ),
    ]
