# Generated by Django 4.1.5 on 2023-01-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_metrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='review',
        ),
        migrations.AddField(
            model_name='metrics',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.DeleteModel(
            name='BotUser',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
